### ISSUE TITLE
ScrollBar is hidden behind headers in TableView

### ISSUE THREAD

**Issue by wiencheck** [TimOliver/TOScrollBar#5]
![img_5541](https://user-images.githubusercontent.com/25985996/33147719-bbd1a742-cfc0-11e7-9ad1-605b6fed8613.PNG)

What's interesting that upon loading it is over the header, but when I start to move it it gets hidden by headers. Is there any workaround for this issue?

**Comment by TimOliver** [comment]
Oh dear. I've never seen that before. I'm guessing it's because the headers are being added as the top layers in the scroll view.

It should be relatively easy to fix. It'll probably mean on every update of the scroll view, the scroll bar needs to be moved to be the top subview. I'll have to add that to the code.

Thanks for the heads-up!

**Comment by TimOliver** [comment]
Alright. I HOPE this didn't end up adding more of a performance hit, but I've now set it that each time the scroll view scrolls, the scroll bar view is explicitly moved to the top level.

Please download the latest copy from `master` and let me know if that fixed the problem for you. :)

**Comment by TimOliver** [comment]
Alright. I pushed a new version to CocoaPods. This should be fixed. Feel free to re-open if you're still having issues!
